app: antoon 
stage: ${env.ENV}

application:
  component: "./node_modules/@sls-next/serverless-component"
  inputs:
    bucketName: "${app}-web-s3-${stage}"
    name:
      defaultLambda: "${app}-lambda-${stage}"
      apiLambda: "${app}-api-lambda-${stage}"
      imageLambda: "${app}-image-lambda-${stage}"
    cloudfront:
      distributionId: ${env.DISTRIBUTION_ID}
    useServerlessTraceTarget: true
